/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.7.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

type VvpColumnMeta struct {
	Name string `json:"name,omitempty"`
	Virtual bool `json:"virtual,omitempty"`
}
